version: '3.8'
services:
    postgres:
        image: postgres:11.11
        restart: "no"
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: password
            POSTGRES_DB: carshop
